### ISSUE TITLE
Crates.io meeting agenda: 13 Dec 2018 21:00 UTC

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/crates-io-cargo-teams#18]
- housekeeping (@ashleygwilliams - 2min)
   - leadership review for Jan 2019
   - membership review
       - are folks interested in joining?
       - should we consider removing inactive members (yet)?
- privacy notice (@ashleygwilliams - 10min)
   - audit of data collect by crates.io
   - write a plain english privacy notice ourselves
      - https://gdpr-info.eu/art-13-gdpr/ point 2
      - "you have to state why you need it/what you're going to do with it. you also need to declare the actions available under gdpr to the user"
- all hands planning (@ashleygwilliams - 5min)
   - who is attending?
   - suggestions for sessions?
      - goal setting
      - policy prioritization and brainstorm
- I'd like to merge the openssl version bump, but don't want to mix it in with all our other pending changes.  Our last deploy was from Oct 25th. (@jtgeibel)
- Scheduling of issue/PR triage meeting (@jtgeibel)
  - Should we try to do something before the new year?

**Comment by sgrif** [comment]
@alexcrichton Have you looked into the DNS stuff more? Is it worth bringing up again at the next meeting?

**Comment by alexcrichton** [comment]
Oh I sent this on the channel a long time ago but sorry forgot to drum up more notice around it! I have indeed looked into it more, and it looks like this - https://gist.github.com/alexcrichton/65f17fe089979a4a359145a8992c67b8

**Comment by sgrif** [comment]
Action items:

- Housekeeping
  - Leadership review to happen Jan 3
  - Too early to remove inactive members, but @ag_dubs to ping existing members to ask if they'd like to continue
  - Folks who have been attending meetings and are interested in joining the team should DM @ag_dubs on Discord
- Privacy notice
  - @sgrif and @jtgeibel to handle audit
  - @ag_dubs will write the policy
- All hands planning
  - Further discussion in #19 
- Large deploy backlog
  - @sgrif has deployed and will be making sure to deploy more often
  - Ops bot to be prioritized
  - @sgrif and @ag_dubs are available to deploy if pinged on Discord
- Issue triage scheduling
  - One meeting next week, then pushing back to new year
