### ISSUE TITLE
Crates.io meeting agenda: 20 Dec 2018 21:00 UTC 

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates-io-cargo-teams#20]
- All Hands Planning Update https://github.com/rust-lang/crates-io-cargo-teams/issues/19 - (@ashleygwilliams - 2min)
- Triage Meeting Update - (@ashleygwilliams - 5min)
- We have [an eRFC filed for our team](https://github.com/rust-lang/rfcs/pull/2614)! Some relevant discussion on [this internals thread](https://internals.rust-lang.org/t/pre-erfc-crate-name-transfer/9027) too. (@carols10cents - 10min)
- crates.io + CloudFront consensus (@ashleygwilliams - 5min)
- stabilize alternative registries (@withoutboats - 5min)

we have 3minutes left on the agenda! if you have additional items, please message @ashleygwilliams on discord directly

**Comment by Centril** [comment]
A PR against https://github.com/anp/rfcbot-rs/blob/master/rfcbot.toml would be welcome to give the team rfcbot powers. :)

**Comment by carols10cents** [comment]
@Centril done! https://github.com/anp/rfcbot-rs/pull/249

**Comment by alexcrichton** [comment]
If possible it'd be nice to make some progress on crates.io + CloudFront consensus, detailed [here](https://gist.github.com/alexcrichton/65f17fe089979a4a359145a8992c67b8)
