### ISSUE TITLE
Crates.io team meeting agenda 2018-01-03

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates-io-cargo-teams#22]
- membership updates (@ashleygwilliams - 5min)
- Issue triage meeting update @sgrif (5 mins)
- Status update of diesel 1.4? (@carols10cents is asking from @sgrif)
- Audit of private information that crates.io stores (@carols10cents added for @ashleygwilliams)
- Ops bot next steps https://github.com/rust-lang/crates-io-cargo-teams/issues/7 (@carols10cents)
- [RFC 2614](https://github.com/rust-lang/rfcs/pull/2614)
- travis-ci.com migration (@pietroalbini)

**Comment by ashleygwilliams** [comment]
TODO: 
- @sgrif @jtgeibel info audit for @ashleygwilliams for privacy notice
- schedule travis migration @pietroalbini 
   - question: bors-ng?
       - was originally because of ease of setup, maybe to test drive features - @carols10cents 
       - @pietroalbini willing to help
       - decision: let's switch!
   - badges: https://github.com/rust-lang/crates.io/issues/1392
- RFC: next week's meeting will be a 1hr voice call, @ashleygwilliams to set up, 30min dedicated to the RFC response
