### ISSUE TITLE
crates.io meeting agenda 2019-01-10

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates-io-cargo-teams#23]
Note: This meeting will be a video call, not in the Discord channel. Anyone who wishes to attend as an observer will need an invitation. Please ping `@sgrif` or `@ag_dubs` in Discord if you are interested in attending as an observer.
--

- [x] Privacy policy audit update @ashleygwilliams 
- [x] [Alternative registries](https://github.com/rust-lang/crates-io-cargo-teams/issues/21) @sgrif (5 min)
- [x] Ops bot update @sgrif & @ashleygwilliams (5 min)
- [x] bors-ng @pietroalbini (5 min)
- [x] Policy on orphaned accounts w/ verified emails @sgrif (5 min)
- [x] Abuse mitigation prioritization/volunteers requested by @carols10cents
  - [Index cleanup](https://github.com/rust-lang/crates.io/issues/1590) - @sgrif will take care of
  - Rate limiting of publish - high priority, @sgrif 
  - Block by account - lower priority
  - Disruption Policy - https://en.wikipedia.org/wiki/Wikipedia:Do_not_disrupt_Wikipedia_to_illustrate_a_point
- [x] Other (5 min - @jtgeibel)
- [ ] ~Website Redesign kickoff (5 min - @ashleygwilliams)~ [postponed to next meeting]
- [ ] [RFC 2614](https://github.com/rust-lang/rfcs/pull/2614)
  - [pre-RFC](https://internals.rust-lang.org/t/pre-erfc-crate-name-transfer/9027)
  - @ashleygwilliams will write a summary comment of what we discussed in the meeting
  - Note: We expect discussion of this item to go over our normal time. If you are interested in being part of the full discussion on this item, plan for the meeting lasting 1 hour instead of the normal 30 minutes

**Comment by ishitatsuyuki** [comment]
Website redesign kick-off, which is postponed from last year (@ashleygwilliams: do you have a time estimate?)
