### ISSUE TITLE
Crates.io meeting agenda: 21 Feb 2019 21:00 UTC, Discord, 30 min

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates-io-cargo-teams#30]
- [x] Privacy policy audit update (@ashleygwilliams/@sgrif) (5 min)
- [x] cloudfront update (@pietroalbini) (10 min)
- [x] roadmap and policy discussion scheduling (@sgrif) (5 min)
- [x] Verified email requirement - Time sensitive, 2019-02-28 is announced date (@carols10cents) (5 min)
  - Need review on https://github.com/rust-lang/crates.io/pull/1621
  - Will have another PR implementing hard error on publish without a verified email with a date check that will need to be deployed before 2019-02-28
  - Will have a PR removing the date check and always erroring to be deployed after 2019-02-28

**Comment by sgrif** [comment]
- @sgrif to follow up with @ashleygwilliams to see if she's willing to hand off the privacy policy work, and take over if so
- `static.crates.io` and `static.rust-lang.org` will be put behind fastly, apex to be put behind cloudfront. @joshtriplett to coordinate with fastly. Additional testing to be done before pulling the trigger on cloudfront
- There will be two 1 hour video calls in the next few weeks to discuss the roadmap and policy stuff from the all hands. @sgrif to coordinate scheduling
- https://github.com/rust-lang/crates.io/pull/1621 to be reviewed promptly, @sgrif will make sure it gets reviewed and/or deployed if there's no changes required tomorrow
