### ISSUE TITLE
Crates.io meeting agenda: 28 Feb 2019 21:00 UTC, Discord, 30 min

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates-io-cargo-teams#31]
@sgrif would you update the title if we're going to have the policy video call this week?

* http://status.crates.io -> https://crates-io.statuspage.io/ is down/inactive.  It's not clear to me if this page, or http://ping.crates.io is our preferred URL, but Googling "crates.io status" points to the currently inactive page.  (reported in channel, added by @jtgeibel)

**Comment by carols10cents** [comment]
This meeting was cancelled. sgrif is going to take care of the credit card issue affecting the status page soon.
