### ISSUE TITLE
Crates.io meeting agenda: 07 March 2019 21:00 UTC, Discord, 30 min

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates-io-cargo-teams#32]
- [Publishing a 28 crate workspace hits the rate limit](https://github.com/rust-lang/crates.io/issues/1643). Carol bumped up the rate limit to 30 publishes/minute as a short term solution to allow this project to publish, what should the long term solution be? (@carols10cents added this but she's not likely to be able to attend the meeting this week)
- Roadmap scheduling update - @sgrif 5 mins

**Comment by sgrif** [comment]
- Rate limiting plan hasn't changed. Once we put in additional more aggressive limiting on new crates we can be much looser with the global rate limit. We still want *some* limit in place there to avoid exposing a DDOS vector, but we can set the burst rate pretty high. 30 seems reasonable unless other folks complain.
- Roadmap meeting will probably be Thursday or Friday next week, still trying to get everyone who wants to be there to respond to the scheduling poll.
