### ISSUE TITLE
crates.io meeting agenda: 2020-07-03 14:30 UTC (Discord, 30 min)

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates-io-cargo-teams#88]
Feel free to edit this to add items to the agenda, or post a comment if you are unable to edit.

# Agenda

* Should we disable the email notification form since the actual notifications are not yet implemented? https://github.com/rust-lang/crates.io/issues/1895

**Comment by jtgeibel** [comment]
rust-lang/crates.io#2603 was opened regarding email notifications.
